{
  "hash": "be0c23d41c6a05a506d781a9de649733",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Date-Time Data Analysis in R\"\ndescription: |\n  A practical guide to working with date and time data.\nauthor: \"Habtamu Bizuayehu\"\nwebsite: \"https://habtamubizuayehu.com/\"\ngithub: \"https://github.com/HabtamuBizuayehu\"\norcid: \"https://orcid.org/0000-0002-1360-4909\"\ndate: 2025-04-14\nimage: \"figure_1.png\"\nhighlight-style: github\noutput-dir: \"docs\"\ncategories: [Data management, Time series analysis]\nformat: \n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: false\n    code-fold: false\n    code-tools: true\n    code-summary: \"Show the code\"\n    theme: united\n    self-contained: true\nknitr: \n  opts_knit: \n    warning: false\n    message: false\neditor: visual\n---\n\n# **Overview of Presentation Contents**\n\nThis presentation introduces essential techniques for analyzing date and time data in health research using R. Key topics include:\n\n-   **Importance of date/time analysis**\n\n-   **Core R packages** for handling dates (e.g., `lubridate`, `tidyverse`)\n\n-   **Date conversion and formatting**\n\n-   **Calculating durations and age**\n\n-   **Extracting date components** (e.g., month, weekday, season)\n\n-   **Summary and Visualize time-based trends**\n\n**1. Importance of Date/Time Analysis in Health Data**\n\nDate-time data is crucial in healthcare because it allows us to:\n\n-   Calculate accurate patient ages, service time\n\n-   Measure time intervals between critical events (e.g., diagnosis to treatment, age vaccination)\n\n-   Identify seasonal patterns in disease occurrence\n\n-   Track vaccine effectiveness over time\n\n-   Determine follow-up periods for clinical studies\n\n\n::: {.cell}\n\f::: {.cell-output .cell-output-stdout}\n\n```\npackage 'flexdashboard' successfully unpacked and MD5 sums checked\n\nThe downloaded binary packages are in\n\tC:\\Users\\User\\AppData\\Local\\Temp\\RtmpgJeQ8n\\downloaded_packages\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n# **Load required libraries**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate) # Simplifies the manipulation of dates and times in R (e.g., formatting, extracting components)\nlibrary(dplyr) # Provides tools for data manipulation, helpful for filtering and summarizing date-based data\nlibrary(stringr) # Simplifies string manipulation\n\nlibrary(zoo) # For working with time series data, including rolling calculations and handling missing data in time series\nlibrary(tsibble) # Provides tools for handling time series data, including date-time indexes and features for forecasting\n\nlibrary(readr) # For reading date-time data from CSV\nlibrary(haven) #  data from other statistical software formats (SPSS, SAS, Stata)\nlibrary(forecast) # Useful for time series forecasting, especially when working with seasonal or trend-based data\nlibrary(ggplot2) # For visualizing date-time trends in data (e.g., time series plots)\nlibrary(janitor) # Tabulation, cleaning column names, adding totals and proportions\nlibrary (plotly)     # Interactive visualizations\n\n# Documentation/reporting\nlibrary(prettydoc)  # Pretty document templates\nlibrary(flexdashboard)# Interactive dashboards\nlibrary(knitr)      # Dynamic report generation\nlibrary(quarto)  # For rendering and publishing documents with the Quarto framework\nlibrary(rmarkdown)  # R Markdown document processing\nlibrary(yaml)       # YAML document processing\n\n# Tabulation\nlibrary(flextable)  # Flexible table formatting\nlibrary(gt)         # Grammar of tables\nlibrary(reactable)  # Interactive tables\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"C:/Users/User/Desktop/Materials_ Course and proposals/Course Related/DataCamp/Data/Synthetic_data\")\n\npatients <- read.csv(\"patients.csv\")\nvaccination <- read.csv(\"immunizations.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert column names to lowercase\ncolnames(patients) <- tolower(colnames(patients))\ncolnames(vaccination) <- tolower(colnames(vaccination))\n\n# View data\n# head(patients)\n# head(vaccination)\n\nstr(patients)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t106 obs. of  28 variables:\n $ id                 : chr  \"30a6452c-4297-a1ac-977a-6a23237c7b46\" \"34a4dcc4-35fb-6ad5-ab98-be285c586a4f\" \"7179458e-d6e3-c723-2530-d4acfe1c2668\" \"37c177ea-4398-fb7a-29fa-70eb3d673876\" ...\n $ birthdate          : chr  \"1994-02-06\" \"1968-08-06\" \"2008-12-21\" \"1994-01-27\" ...\n $ deathdate          : chr  \"\" \"2009-12-11\" \"\" \"\" ...\n $ ssn                : chr  \"999-52-8591\" \"999-75-3953\" \"999-70-1925\" \"999-27-9779\" ...\n $ drivers            : chr  \"S99996852\" \"S99993577\" \"\" \"S99995100\" ...\n $ passport           : chr  \"X47758697X\" \"X28173268X\" \"\" \"X83694889X\" ...\n $ prefix             : chr  \"Mr.\" \"Mr.\" \"\" \"Mrs.\" ...\n $ first              : chr  \"Joshua658\" \"Bennie663\" \"Hunter736\" \"Carlyn477\" ...\n $ middle             : chr  \"Alvin56\" \"\" \"Mckinley734\" \"Florencia449\" ...\n $ last               : chr  \"Kunde533\" \"Ebert178\" \"Gerlach374\" \"Williamson769\" ...\n $ suffix             : logi  NA NA NA NA NA NA ...\n $ maiden             : chr  \"\" \"\" \"\" \"Rogahn59\" ...\n $ marital            : chr  \"M\" \"D\" \"\" \"M\" ...\n $ race               : chr  \"white\" \"white\" \"white\" \"asian\" ...\n $ ethnicity          : chr  \"nonhispanic\" \"nonhispanic\" \"nonhispanic\" \"nonhispanic\" ...\n $ gender             : chr  \"M\" \"M\" \"M\" \"F\" ...\n $ birthplace         : chr  \"Boston  Massachusetts  US\" \"Chicopee  Massachusetts  US\" \"Spencer  Massachusetts  US\" \"Franklin  Massachusetts  US\" ...\n $ address            : chr  \"811 Kihn Viaduct\" \"975 Pfannerstill Throughway\" \"548 Heller Lane\" \"160 Fadel Crossroad Apt 65\" ...\n $ city               : chr  \"Braintree\" \"Braintree\" \"Mattapoisett\" \"Wareham\" ...\n $ state              : chr  \"Massachusetts\" \"Massachusetts\" \"Massachusetts\" \"Massachusetts\" ...\n $ county             : chr  \"Norfolk County\" \"Norfolk County\" \"Plymouth County\" \"Plymouth County\" ...\n $ fips               : int  25021 25021 NA NA NA 25017 25017 25021 25009 NA ...\n $ zip                : int  2184 2184 0 0 0 2138 2476 2184 1835 0 ...\n $ lat                : num  42.2 42.3 41.6 41.8 42.7 ...\n $ lon                : num  -71 -71 -70.9 -70.7 -71 ...\n $ healthcare_expenses: num  56905 124024 45645 12895 18500 ...\n $ healthcare_coverage: num  18020 1075 6155 659952 5494 ...\n $ income             : int  100511 49737 133816 17382 52159 75767 58294 49737 77756 35255 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(vaccination)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t1619 obs. of  6 variables:\n $ date       : chr  \"2016-04-10T09:04:48Z\" \"2016-04-10T09:04:48Z\" \"2016-04-10T09:04:48Z\" \"2016-04-10T09:04:48Z\" ...\n $ patient    : chr  \"30a6452c-4297-a1ac-977a-6a23237c7b46\" \"30a6452c-4297-a1ac-977a-6a23237c7b46\" \"30a6452c-4297-a1ac-977a-6a23237c7b46\" \"30a6452c-4297-a1ac-977a-6a23237c7b46\" ...\n $ encounter  : chr  \"0b03e41b-06a6-66fa-b972-acc5a83b134a\" \"0b03e41b-06a6-66fa-b972-acc5a83b134a\" \"0b03e41b-06a6-66fa-b972-acc5a83b134a\" \"0b03e41b-06a6-66fa-b972-acc5a83b134a\" ...\n $ code       : int  140 113 43 114 140 140 140 140 140 52 ...\n $ description: chr  \"Influenza  seasonal  injectable  preservative free\" \"Td (adult)  5 Lf tetanus toxoid  preservative free  adsorbed\" \"Hep B  adult\" \"meningococcal MCV4P\" ...\n $ base_cost  : num  136 136 136 136 136 136 136 136 136 136 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check for missing IDs\npatients$id[patients$id == \"\"] <- NA\nprint(sum(is.na(patients$id)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check duplicates\npatients <- patients %>%\n  arrange(id) %>%\n  group_by(id) %>%\n  mutate(dup = row_number()) %>%\n  ungroup()\n\ntable(patients$dup)  # Check if any duplicates exist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1 \n106 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Merge with vaccination data\nvaccination <- vaccination %>% mutate(id = patient)\n\n\nvacc_pt_merged <- left_join(patients, vaccination, by = \"id\" )\n\n#vacc_pt_merged <- left_join(patients, vaccination, by = c(\"id\" = \"patient\"))\n\nstr (vacc_pt_merged)\n```\n:::\n\n\n# Converting Character to Date Format\n\nin the dataset `birthdate`, `deathdate`, and `date` (vaccination date) are all stored as character strings. I need to convert these to proper date formats using `lubridate::ymd()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert to date format\nstr (vacc_pt_merged$birthdate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n chr [1:1619] \"1975-12-24\" \"1975-12-24\" \"1975-12-24\" \"1975-12-24\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nstr (vacc_pt_merged$date) # date is YYYY-MM-DD HH:MM:SS format.\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n chr [1:1619] \"2015-06-24T14:05:28Z\" \"2016-06-29T14:05:28Z\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nvacc_pt_merged <- vacc_pt_merged %>%\n  mutate(\n    birthdate = parse_date(birthdate, format = \"%Y-%m-%d\"),\n    vacc_date = as.Date(strptime(date, format = \"%Y-%m-%dT%H:%M:%SZ\"))\n  )\n\n# Check structure\nstr (vacc_pt_merged$birthdate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Date[1:1619], format: \"1975-12-24\" \"1975-12-24\" \"1975-12-24\" \"1975-12-24\" \"1975-12-24\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nstr (vacc_pt_merged$vacc_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Date[1:1619], format: \"2015-06-24\" \"2016-06-29\" \"2016-06-29\" \"2017-07-05\" \"2017-07-05\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check converted formats via glimpse\n# glimpse(vacc_pt_merged)\n\n# no missing values on dates\nsum(is.na(vacc_pt_merged$birthdate)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(vacc_pt_merged$vacc_date))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check date ranges\nsummary(vacc_pt_merged$birthdate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. \n\"1914-03-03\" \"1969-12-09\" \"1999-02-24\" \"1990-12-03\" \"2012-09-02\" \"2023-03-01\" \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(vacc_pt_merged$vacc_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. \n\"1962-12-09\" \"2017-05-21\" \"2020-01-04\" \"2019-04-29\" \"2022-01-26\" \"2024-10-26\" \n```\n\n\n:::\n:::\n\n\nNow date columns are in Date format (`YYYY-MM-DD`), ready for analysis!\n\n# **Age and Service year Calculation**\n\nAge at the time of vaccination is essential. Here’s how I calculate it in **years**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacc_pt_merged <- vacc_pt_merged %>%\n  mutate(\n    age_years = floor (as.numeric(difftime(Sys.Date(), birthdate, units = \"days\")) / 365.25),\n    \n    # Calculate vaccination service year by extracting the year from vacc_date\n   vacc_service_year = year(vacc_date)\n  )\n\n\nsummary(vacc_pt_merged$age_years)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    2.0    13.0    26.0    34.4    55.0   111.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(vacc_pt_merged$vacc_service_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1962    2017    2020    2019    2022    2024 \n```\n\n\n:::\n\n```{.r .cell-code}\n# tabulation\ntable(vacc_pt_merged$age_years)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  2   3   6   7   8  10  11  12  13  14  15  16  17  18  19  20  21  22  24  25 \n 46  24  64  66  34  72  30  38  59  21  21  51  66  18  36  18  69  13  13  12 \n 26  28  29  30  31  34  37  38  39  41  42  44  45  46  47  48  49  50  52  53 \n 47  17  30   9  38  11   6   8   6  27  46   9  17  15  13  18  42  15  13  30 \n 54  55  56  57  59  61  62  63  65  66  69  70  72  73  75  77  79  81  86  98 \n 16  15  15  30  14  26  13  62  26  14  14  57  15  27  15  14  12  13  12  20 \n111 \n  1 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(vacc_pt_merged$vacc_service_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 2001 2002 2003 2004 2005 2006 \n   1    3    1    1    1    2    1    1    1    1    1    2    1    1    2    1 \n2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 \n   3    6    2    3    2    4    3   22  153  139  137  151  161  137  263  120 \n2023 2024 \n 170  122 \n```\n\n\n:::\n:::\n\n\nAs shown above, the **average age at vaccination** was approximately 34.4 years, with a range from 2 to 111 years.\n\nThe **highest frequency of vaccinations** occurred in the year 2021, suggesting a peak in service delivery during that period.\n\n# **Calculating Time Differences**\n\nTo calculate time differences, I use `interval()` or simple subtraction between date objects.\n\nExample: Years between birth and vaccination gives the **number of years from birth to vaccination**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacc_pt_merged <- vacc_pt_merged %>%\n  mutate(\n    days_to_vax = as.numeric(vacc_date - birthdate),  # Difference in days\n    weeks_to_vax = as.numeric(difftime(vacc_date,  birthdate,  units = \"weeks\")),  # Difference in weeks\n    months_to_vax = as.numeric(difftime(vacc_date,  birthdate,  units = \"days\")) / 30.44,  # Approximate months (average days per month)\n    years_to_vax = floor(as.numeric(difftime(vacc_date,  birthdate,  units = \"days\")) / 365.25)  # Approximate years (including leap years)\n  )\n\n\n# View summary statistics \nsummary(vacc_pt_merged$days_to_vax)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      0    2548    7742   10375   18263   36813 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(vacc_pt_merged$weeks_to_vax)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      0     364    1106    1482    2609    5259 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(vacc_pt_merged$months_to_vax)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00   83.71  254.34  340.82  599.97 1209.36 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(vacc_pt_merged$years_to_vax)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    6.00   21.00   28.02   50.00  100.00 \n```\n\n\n:::\n:::\n\n\n# **Extracting Date Components**\n\nWe will perform the following extractions for both the `birthdate` and `vaccination date`:\n\n1.  **Day**: The day of the month is extracted using the `day()` function.\n\n2.  **Month**: The month of the date is obtained with the `month()` function. This provides a numeric value (1 for January, 12 for December).\n\n3.  **Year**: The year component is retrieved using the `year()` function, returning a four-digit value for the year.\n\n4.  **Quarter**: The quarter of the year is extracted using the `quarter()` function, providing a numeric value from 1 to 4, representing the first through fourth quarter of the year.\n\n5.  **Season**: Based on the month, we assign a corresponding season (Summer, Autumn, Winter, or Spring) using a conditional `case_when()` function:\n\nThese components are useful for segmenting the data, performing seasonal analysis, and understanding how different periods influence the patterns observed in the data. For instance, analyzing vaccination trends by quarter or season can provide valuable insights into public health strategies.\n\nBy extracting these components, we are preparing the data for more granular analysis, including cohort analysis, seasonal trend assessments, and other forms of time-based grouping.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacc_pt_merged <- vacc_pt_merged %>%\n  mutate(\n    # Basic date components\n    vacc_day = day(vacc_date),\n    vacc_month = month(vacc_date),\n    vacc_month_name = month(vacc_date, label = TRUE, abbr = FALSE),  # Full month name\n    vacc_year = year(vacc_date),\n    vacc_weekday = wday(vacc_date, label = TRUE, abbr = FALSE),     # Full weekday name\n    vacc_week = week(vacc_date),                                    # Week of year\n    vacc_quarter = quarter(vacc_date),\n    \n    # Fiscal year (assuming June start)\n    vacc_fy = ifelse(vacc_month >= 6, vacc_year, vacc_year - 1),\n    \n    # Season (Northern Hemisphere)\n    vacc_season = case_when(\n      vacc_month %in% 3:5 ~ \"Spring\",\n      vacc_month %in% 6:8 ~ \"Summer\",\n      vacc_month %in% 9:11 ~ \"Autumn\",\n      TRUE ~ \"Winter\"  # December-February\n    ),\n    \n    # Weekend flag\n    is_weekend = wday(vacc_date) %in% c(1, 7),  # 1=Sunday, 7=Saturday\n    \n    # Days since specific reference date (e.g., pandemic start)\n    days_since_ref = floor(as.numeric(vacc_date - as.Date(\"2020-01-01\")))\n  )\n```\n:::\n\n\n# Filtering Between Date Ranges\n\nFiltering data based on specific date ranges is a common operation in data analysis, particularly when focusing on subsets of data that fall within particular periods. In R, the `dplyr` package provides an intuitive way to filter rows within a specific date range.\n\nBelow is an example of how to filter rows based on dates that fall between two specified dates using the `filter()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter only vaccinations in 2022\nvacc_2022 <- vacc_pt_merged %>%\n  filter(vacc_date >= ymd(\"2022-01-01\") & vacc_date <= ymd(\"2022-12-31\"))\n\n# Filter vaccinations between 2015 and 2024\nvacc_1524 <- vacc_pt_merged %>%\n  filter(vacc_service_year >= 2015 & vacc_service_year <= 2024)\n         \n\ntable(vacc_1524$vacc_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 \n 153  139  137  151  161  137  263  120  170  122 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(vacc_1524$race)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n asian  black native  other  white \n   111     94     13     29   1306 \n```\n\n\n:::\n\n```{.r .cell-code}\n# table(vacc_1524$ethnicity)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ordering variables for visual checking \nvacc_1524 <- vacc_1524 %>% \n  select(id, gender, race, birthdate, date, vacc_date, age_years, vacc_service_year, days_to_vax, weeks_to_vax, \n         months_to_vax, years_to_vax, vacc_day, vacc_month, vacc_month_name, vacc_year, vacc_weekday, vacc_week, \n         vacc_quarter, vacc_fy, vacc_season, is_weekend, days_since_ref, everything())\n```\n:::\n\n\n# Summary of vaccination pattern: Tabulation -----------------------------------\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Recode gender\nvacc_1524 <- vacc_1524 %>%\n  mutate(gender = case_when(\n    gender == \"F\" ~ \"Female\",\n    gender == \"M\" ~ \"Male\",\n    TRUE ~ gender\n  ))\n\n# Convert time variables to character for consistency\nvacc_1524 <- vacc_1524 %>%\n  mutate(across(c(vacc_service_year, vacc_quarter, vacc_weekday), as.character))\n\n# Create and label each table\ntab_year <- vacc_1524 %>%\n  tabyl(vacc_service_year, gender) %>%\n  adorn_totals(\"row\") %>%\n  mutate(Category = \"Year\", .before = 1) %>%\n  rename(Label = vacc_service_year)\n\ntab_quarter <- vacc_1524 %>%\n  tabyl(vacc_quarter, gender) %>%\n  adorn_totals(\"row\") %>%\n  mutate(Category = \"Quarter\", .before = 1) %>%\n  rename(Label = vacc_quarter)\n\ntab_weekday <- vacc_1524 %>%\n  tabyl(vacc_weekday, gender) %>%\n  adorn_totals(\"row\") %>%\n  mutate(Category = \"Weekday\", .before = 1) %>%\n  rename(Label = vacc_weekday)\n\n# Combine all\ntab_combined <- bind_rows(tab_year, tab_quarter, tab_weekday)\n\n# Calculate column proportions within each Category group (excluding \"Total\" row)\ntab_combined <- tab_combined %>%\n  group_by(Category) %>%\n  mutate(\n    Female_Prop = round(100 * Female / sum(Female[Label != \"Total\"]), 1),\n    Male_Prop = round(100 * Male / sum(Male[Label != \"Total\"]), 1)\n  ) %>%\n  ungroup()\n\n# Format with flextable\nft <- flextable(tab_combined) %>%\n  set_header_labels(\n    Category = \"Time Unit\",\n    Label = \"Category\",\n    Female = \"Female Count\",\n    Male = \"Male Count\",\n    Female_Prop = \"Female %\",\n    Male_Prop = \"Male %\"\n  ) %>%\n  add_header_lines(values = \"Table: Vaccination counts and gender proportions (%) across Year, Quarter, and Weekday\") %>%\n  theme_box() %>%\n  autofit()\n\nft\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-7867f5da{}.cl-785bcf08{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-785bcf1c{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-78602abc{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-78602ac6{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-786059ce{width:0.981in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059d8{width:1.092in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059d9{width:1.295in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059e2{width:1.108in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059e3{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059ec{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059ed{width:0.981in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059ee{width:1.092in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059f6{width:1.295in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-786059f7{width:1.108in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a00{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a01{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a0a{width:0.981in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a0b{width:1.092in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a0c{width:1.295in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a14{width:1.108in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a15{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a1e{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a1f{width:0.981in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a20{width:1.092in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a28{width:1.295in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a29{width:1.108in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a32{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a33{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a3c{width:0.981in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a3d{width:1.092in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a46{width:1.295in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a50{width:1.108in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a51{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a52{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a5a{width:0.981in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a5b{width:1.092in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a5c{width:1.295in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a64{width:1.108in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a65{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-78605a6e{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-7867f5da'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"6\"class=\"cl-786059ce\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf08\">Table: Vaccination counts and gender proportions (%) across Year, Quarter, and Weekday</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-786059ce\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf08\">Time Unit</span></p></th><th class=\"cl-786059d8\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf08\">Category</span></p></th><th class=\"cl-786059d9\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf08\">Female Count</span></p></th><th class=\"cl-786059e2\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf08\">Male Count</span></p></th><th class=\"cl-786059e3\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf08\">Female %</span></p></th><th class=\"cl-786059ec\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf08\">Male %</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-786059ed\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-786059ee\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2015</span></p></td><td class=\"cl-786059f6\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">74</span></p></td><td class=\"cl-786059f7\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">79</span></p></td><td class=\"cl-78605a00\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">9.3</span></p></td><td class=\"cl-78605a01\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">10.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a0a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a0b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2016</span></p></td><td class=\"cl-78605a0c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">77</span></p></td><td class=\"cl-78605a14\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">62</span></p></td><td class=\"cl-78605a15\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">9.6</span></p></td><td class=\"cl-78605a1e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">8.2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a0a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a0b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2017</span></p></td><td class=\"cl-78605a0c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">65</span></p></td><td class=\"cl-78605a14\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">72</span></p></td><td class=\"cl-78605a15\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">8.1</span></p></td><td class=\"cl-78605a1e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">9.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a0a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a0b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2018</span></p></td><td class=\"cl-78605a0c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">97</span></p></td><td class=\"cl-78605a14\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">54</span></p></td><td class=\"cl-78605a15\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">12.2</span></p></td><td class=\"cl-78605a1e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">7.2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a1f\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a20\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2019</span></p></td><td class=\"cl-78605a28\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">78</span></p></td><td class=\"cl-78605a29\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">83</span></p></td><td class=\"cl-78605a32\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">9.8</span></p></td><td class=\"cl-78605a33\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">11.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a0a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a0b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2020</span></p></td><td class=\"cl-78605a0c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">61</span></p></td><td class=\"cl-78605a14\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">76</span></p></td><td class=\"cl-78605a15\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">7.6</span></p></td><td class=\"cl-78605a1e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">10.1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a1f\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a20\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2021</span></p></td><td class=\"cl-78605a28\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">146</span></p></td><td class=\"cl-78605a29\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">117</span></p></td><td class=\"cl-78605a32\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">18.3</span></p></td><td class=\"cl-78605a33\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">15.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a0a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a0b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2022</span></p></td><td class=\"cl-78605a0c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">61</span></p></td><td class=\"cl-78605a14\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">59</span></p></td><td class=\"cl-78605a15\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">7.6</span></p></td><td class=\"cl-78605a1e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">7.8</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a1f\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a20\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2023</span></p></td><td class=\"cl-78605a28\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">82</span></p></td><td class=\"cl-78605a29\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">88</span></p></td><td class=\"cl-78605a32\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">10.3</span></p></td><td class=\"cl-78605a33\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">11.7</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a0a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a0b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2024</span></p></td><td class=\"cl-78605a0c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">57</span></p></td><td class=\"cl-78605a14\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">65</span></p></td><td class=\"cl-78605a15\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">7.1</span></p></td><td class=\"cl-78605a1e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">8.6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a0a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Year</span></p></td><td class=\"cl-78605a0b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Total</span></p></td><td class=\"cl-78605a0c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">798</span></p></td><td class=\"cl-78605a14\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">755</span></p></td><td class=\"cl-78605a15\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">100.0</span></p></td><td class=\"cl-78605a1e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">100.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a3c\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Quarter</span></p></td><td class=\"cl-78605a3d\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">1</span></p></td><td class=\"cl-78605a46\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">174</span></p></td><td class=\"cl-78605a50\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">229</span></p></td><td class=\"cl-78605a51\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">21.8</span></p></td><td class=\"cl-78605a52\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">30.3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a3c\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Quarter</span></p></td><td class=\"cl-78605a3d\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">2</span></p></td><td class=\"cl-78605a46\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">230</span></p></td><td class=\"cl-78605a50\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">146</span></p></td><td class=\"cl-78605a51\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">28.8</span></p></td><td class=\"cl-78605a52\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">19.3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a3c\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Quarter</span></p></td><td class=\"cl-78605a3d\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">3</span></p></td><td class=\"cl-78605a46\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">205</span></p></td><td class=\"cl-78605a50\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">262</span></p></td><td class=\"cl-78605a51\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">25.7</span></p></td><td class=\"cl-78605a52\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">34.7</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a3c\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Quarter</span></p></td><td class=\"cl-78605a3d\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">4</span></p></td><td class=\"cl-78605a46\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">189</span></p></td><td class=\"cl-78605a50\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">118</span></p></td><td class=\"cl-78605a51\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">23.7</span></p></td><td class=\"cl-78605a52\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">15.6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a3c\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Quarter</span></p></td><td class=\"cl-78605a3d\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Total</span></p></td><td class=\"cl-78605a46\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">798</span></p></td><td class=\"cl-78605a50\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">755</span></p></td><td class=\"cl-78605a51\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">100.0</span></p></td><td class=\"cl-78605a52\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">100.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a5a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-78605a5b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Friday</span></p></td><td class=\"cl-78605a5c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">69</span></p></td><td class=\"cl-78605a64\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">111</span></p></td><td class=\"cl-78605a65\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">8.6</span></p></td><td class=\"cl-78605a6e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">14.7</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a5a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-78605a5b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Monday</span></p></td><td class=\"cl-78605a5c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">117</span></p></td><td class=\"cl-78605a64\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">60</span></p></td><td class=\"cl-78605a65\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">14.7</span></p></td><td class=\"cl-78605a6e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">7.9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-786059ce\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-786059d8\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Saturday</span></p></td><td class=\"cl-786059d9\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">171</span></p></td><td class=\"cl-786059e2\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">82</span></p></td><td class=\"cl-786059e3\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">21.4</span></p></td><td class=\"cl-786059ec\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">10.9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-786059ce\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-786059d8\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Sunday</span></p></td><td class=\"cl-786059d9\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">153</span></p></td><td class=\"cl-786059e2\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">124</span></p></td><td class=\"cl-786059e3\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">19.2</span></p></td><td class=\"cl-786059ec\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">16.4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a5a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-78605a5b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Thursday</span></p></td><td class=\"cl-78605a5c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">118</span></p></td><td class=\"cl-78605a64\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">135</span></p></td><td class=\"cl-78605a65\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">14.8</span></p></td><td class=\"cl-78605a6e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">17.9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a5a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-78605a5b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Tuesday</span></p></td><td class=\"cl-78605a5c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">79</span></p></td><td class=\"cl-78605a64\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">86</span></p></td><td class=\"cl-78605a65\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">9.9</span></p></td><td class=\"cl-78605a6e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">11.4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a5a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-78605a5b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Wednesday</span></p></td><td class=\"cl-78605a5c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">91</span></p></td><td class=\"cl-78605a64\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">157</span></p></td><td class=\"cl-78605a65\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">11.4</span></p></td><td class=\"cl-78605a6e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">20.8</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-78605a5a\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Weekday</span></p></td><td class=\"cl-78605a5b\"><p class=\"cl-78602abc\"><span class=\"cl-785bcf1c\">Total</span></p></td><td class=\"cl-78605a5c\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">798</span></p></td><td class=\"cl-78605a64\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">755</span></p></td><td class=\"cl-78605a65\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">100.0</span></p></td><td class=\"cl-78605a6e\"><p class=\"cl-78602ac6\"><span class=\"cl-785bcf1c\">100.0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n📝 **Summary of Vaccination Uptake by Gender and Time Period**\n\nThe table Aabove presents vaccination counts and gender proportions across different time units—**year, quarter, and weekday**—for individuals aged 15–24 years.\n\n#### **By Year**\n\n-   **2021** recorded the **highest vaccination uptake** for both **females (146; 18.3%)** and **males (117; 15.5%)**, indicating a peak in vaccine distribution during that year.\n\n-   The **lowest uptake** was observed in **2017 for females (65; 8.1%)** and in **2016 for males (62; 8.2%)**.\n\n    Overall, vaccination was more evenly distributed across years, but there was a noticeable increase in 2021, likely due to public health initiatives during the COVID-19 pandemic.\n\n    #### **By Quarter**\n\n-   For **females**, the highest uptake was in **Quarter 2 (230; 28.8%)**, followed by **Quarter 3 (205; 25.7%)**.\n\n-   For **males**, **Quarter 3 (262; 34.7%)** had the highest uptake, while **Quarter 2 (146; 19.3%)** was lower in comparison.\n\n    **Quarter 1** showed the **lowest female uptake proportionally (21.8%)**, while **Quarter 4** had the lowest for males (15.6%).\n\n#### **By Weekday**\n\n-   **Wednesday (157; 20.8%)** was the peak for males.\n\n-   **Friday (14.7%)** and **Thursday (17.9%)** were more popular among males.\n\n-   **Monday had the lowest male uptake (7.9%)**, while **Tuesday (9.9%)** was the lowest for females.\n\n# 📊 Visualizing Vaccination Trends\n\nTime-based visualizations help us uncover trends, seasonality, and variation in vaccination data. Below are some examples of how to visualize date information using the `vacc_pt_merged` dataset. These plots support evidence-based insights and can guide public health decision-making.\n\n#### **Overall Vaccination Patterns by by Gender and Race**\n\n-   **2021** was a notable year across most racial groups, with **peaks in vaccination uptake**, likely due to intensified COVID-19 vaccine rollouts.\n\n-   The **“Other” racial group** showed the **most fluctuation** with a sharp spike in 2023.\n\n-   The **White group** had the **most consistent trend**, while **Asian and Black groups** showed spikes at specific periods.\n\n-   **Females showed a sharper peak** than males in 2021 but also had a **steeper decline afterward**.\n\n-   **Males had more consistent trends overall**, especially from 2015–2020 and 2022–2024.\n\n-   The **post-2021 decline** in both groups may suggest reduced urgency or campaign intensity in recent years\n\n-   Post-2021, a general **decline across all groups** suggests possible vaccine fatigue or the end of mass campaign periods.\n\n-   Variations of vaccination uptake by gender and race are evident, suggesting differing levels of access, trust, or outreach effectiveness across communities.\n\n### Monthly Vaccination Trend in each Year\n\nUse a line plot to visualize how the number of vaccinations changes over time.\n\nThe time series reveals longitudinal patterns, showing potential campaign effects (peaks) or service interruptions (troughs). The upward trend in mid 2021 suggests successful program for vaccination.\n\nAs shown in the monthly vaccination pattern,\n\n-   A **bi-modal pattern** is evident with two peaks (March and August) and two noticeable dips (June and November).\n\n-   **March and August** are peak months — possibly due to public health campaigns.\n\n-   **November** was the lowest — possibly due to holiday distractions, reduced outreach, or end-of-year slowdowns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacc_1524 %>%\n  count(vacc_year, vacc_month) %>%\n  ggplot(aes(x = as.Date(paste(vacc_year, vacc_month, \"01\", sep = \"-\")), \n             y = n)) +\n  geom_line(color = \"#1f78b4\", linewidth = 1) +\n  geom_point(color = \"#33a02c\") +\n  labs(title = \"Monthly Vaccination Trends\",\n       x = \"Timeline\", y = \"Vaccinations\") +\n  scale_x_date(date_labels = \"%b %Y\", date_breaks = \"3 months\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){fig-alt='Monthly vaccination trends over years' width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacc_1524 %>%\n  mutate(month = month(vacc_date, label = TRUE, abbr = TRUE)) %>%  # Extract month from date\n  group_by(month) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  ggplot(aes(x = month, y = count, group = 1)) +\n  \n  geom_line(linewidth = 1, color = \"steelblue\") +\n  geom_point(size = 2, color = \"steelblue\") +\n  labs(\n    title = \"Total Vaccinations by Month\",\n    x = \"Month\",\n    y = \"Vaccination Count\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## **Weekday Heatmap**\n\nThe heatmap identifies temporal service patterns. Higher intensity on Wednesdays/Thursdays may reflect clinic scheduling norms, while weekend gaps could indicate access barriers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacc_1524 %>%\n  count(vacc_month_name, vacc_weekday) %>%\n  ggplot(aes(x = vacc_weekday, y = vacc_month_name, fill = n)) +\n  geom_tile(color = \"white\") +\n  scale_fill_gradient(low = \"#f7fbff\", high = \"#08306b\") +\n  labs(title = \"Vaccination Intensity by Weekday and Month\",\n       x = \"Weekday\", y = \"Month\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){fig-alt='Heatmap of vaccinations by weekday and month' width=672}\n:::\n:::\n\n\n## **Seasonal Vaccination Distribution**\n\nExplore how vaccination services vary by season.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacc_1524 %>%\n  mutate(month = as.numeric(format(vacc_date, \"%m\")),\n         season = case_when(\n           month %in% c(12, 1, 2) ~ \"Summer\",\n           month %in% c(3, 4, 5) ~ \"Autumn\",\n           month %in% c(6, 7, 8) ~ \"Winter\",\n           month %in% c(9, 10, 11) ~ \"Spring\"\n         )) %>%\n  count(season) %>%\n  ggplot(aes(x = season, y = n, fill = season)) +\n  geom_col() +\n  labs(\n    title = \"Seasonal Vaccination Distribution\",\n    x = \"Season\",\n    y = \"Vaccination Count\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Vaccination proportion by year and race\n\nIf we'd like a stacked bar plot of the proportions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Proportion by vacc_year and race with cleaned race labels\ndf_plot_race <- vacc_1524 %>%\n  mutate(\n    race = ifelse(race %in% c(\"native\", \"other\"), \"Other\", race),\n    race = str_to_title(race),\n    vacc_year = as.integer(floor(as.numeric(vacc_year)))  # Ensure whole number\n  ) %>%\n  group_by(race, vacc_year) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  group_by(race) %>%\n  mutate(\n    total = sum(count),\n    proportion = (count / total) * 100\n  ) %>%\n  ungroup()\n\n# Line plot\nggplot(df_plot_race, aes(x = vacc_year, y = proportion, color = race)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  scale_x_continuous(breaks = seq(min(df_plot_race$vacc_year), max(df_plot_race$vacc_year), by = 2)) +\n  labs(\n    title = \"Vaccination Proportion by Race and Year\",\n    x = \"Vaccination Year\",\n    y = \"Proportion (%)\",\n    color = \"Race\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Bar plot\nggplot(df_plot_race, aes(x = vacc_year, y = proportion, fill = race)) +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  scale_x_continuous(breaks = seq(min(df_plot_race$vacc_year), max(df_plot_race$vacc_year), by = 2)) +\n  labs(\n    title = \"Vaccination Proportion by Race and Year\",\n    x = \"Vaccination Year\",\n    y = \"Proportion (%)\",\n    fill = \"Race\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Proportion by vacc_year and gender\nvacc_1524 %>%\n  mutate(\n    gender = case_when(\n      gender == \"M\" ~ \"Male\",\n      gender == \"F\" ~ \"Female\",\n      TRUE ~ gender\n    ),\n    vacc_year = as.integer(vacc_year)  # Ensure year is whole number\n  ) %>%\n  group_by(gender, vacc_year) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  group_by(gender) %>%\n  mutate(\n    total = sum(count),\n    proportion = (count / total) * 100\n  ) %>%\n  ungroup() %>% \n  \n  ggplot(aes(x = vacc_year, y = proportion, color = gender)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  scale_x_continuous(breaks = scales::pretty_breaks()) +  # Ensures whole number years\n  labs(\n    title = \"Vaccination Proportion by Gender and Year\",\n    x = \"Vaccination Year\",\n    y = \"Proportion (%)\",\n    color = \"Gender\"\n  ) +\n  scale_color_manual(values = c(\"Male\" = \"#1f77b4\", \"Female\" = \"#ff7f0e\")) +\n  theme_minimal() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    axis.title = element_text(size = 12),\n    legend.title = element_text(size = 12)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n## Vaccination proportion by month and year\n\n## **Summary and Key Takeaways**\n\nKey techniques covered:\n\n1.  Proper date conversion from character strings\n\n2.  Accurate age and time difference calculations\n\n3.  Seasonal and temporal pattern analysis\n\n4.  Visualization of date-based trends\n\n5.  Survival analysis for time-to-event data\n\nBest practices:\n\n-   Always validate date conversions\n\n-   Document time units clearly (days vs. months vs. years)\n\n-   Handle missing dates explicitly\n\n-   Consider time zones for multi-center studies\n\n**References**\n\n1.  https://CRAN.R-project.org/package=dplyr\n2.  https://www.jstatsoft.org/article/view/v103i01\n3.  https://r4ds.hadley.nz/\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}